baseURL = "https://catdevurandom.com"
theme = "hugo-bearcub"
title = "cat /dev/urandom"
copyright = "All rights reserved"

enableRobotsTXT = true

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[params]
  description = "Random thoughts from a random cat"
  dateFormat = "2006-01-02"
